version: '3.8'

services:

  api:
    build: ./app
    networks:
      - app-network

  front:
    build:
      #./front
      context: front
      target: prod
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - api
      - front
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
